<a href="https://colab.research.google.com/github/brahm-gh/ML-projects/blob/main/Iris_species.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Iris Species

I will be using an iris species dataset to classify iris species based on different factors relating to petal and sepal dimensions.
dataset: https://www.kaggle.com/uciml/iris?select=Iris.csv

In [197]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [198]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [199]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [200]:
X_y = df.iloc[:,1:].values

In [201]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_y[:, -1] = le.fit_transform(X_y[:, -1])

In [202]:
print(X_y)

[[5.1 3.5 1.4 0.2 0]
 [4.9 3.0 1.4 0.2 0]
 [4.7 3.2 1.3 0.2 0]
 [4.6 3.1 1.5 0.2 0]
 [5.0 3.6 1.4 0.2 0]
 [5.4 3.9 1.7 0.4 0]
 [4.6 3.4 1.4 0.3 0]
 [5.0 3.4 1.5 0.2 0]
 [4.4 2.9 1.4 0.2 0]
 [4.9 3.1 1.5 0.1 0]
 [5.4 3.7 1.5 0.2 0]
 [4.8 3.4 1.6 0.2 0]
 [4.8 3.0 1.4 0.1 0]
 [4.3 3.0 1.1 0.1 0]
 [5.8 4.0 1.2 0.2 0]
 [5.7 4.4 1.5 0.4 0]
 [5.4 3.9 1.3 0.4 0]
 [5.1 3.5 1.4 0.3 0]
 [5.7 3.8 1.7 0.3 0]
 [5.1 3.8 1.5 0.3 0]
 [5.4 3.4 1.7 0.2 0]
 [5.1 3.7 1.5 0.4 0]
 [4.6 3.6 1.0 0.2 0]
 [5.1 3.3 1.7 0.5 0]
 [4.8 3.4 1.9 0.2 0]
 [5.0 3.0 1.6 0.2 0]
 [5.0 3.4 1.6 0.4 0]
 [5.2 3.5 1.5 0.2 0]
 [5.2 3.4 1.4 0.2 0]
 [4.7 3.2 1.6 0.2 0]
 [4.8 3.1 1.6 0.2 0]
 [5.4 3.4 1.5 0.4 0]
 [5.2 4.1 1.5 0.1 0]
 [5.5 4.2 1.4 0.2 0]
 [4.9 3.1 1.5 0.1 0]
 [5.0 3.2 1.2 0.2 0]
 [5.5 3.5 1.3 0.2 0]
 [4.9 3.1 1.5 0.1 0]
 [4.4 3.0 1.3 0.2 0]
 [5.1 3.4 1.5 0.2 0]
 [5.0 3.5 1.3 0.3 0]
 [4.5 2.3 1.3 0.3 0]
 [4.4 3.2 1.3 0.2 0]
 [5.0 3.5 1.6 0.6 0]
 [5.1 3.8 1.9 0.4 0]
 [4.8 3.0 1.4 0.3 0]
 [5.1 3.8 1.6 0.2 0]
 [4.6 3.2 1.4

In [203]:
X = X_y[:, :-1]
y = X_y[:, -1].astype('int')

In [204]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [205]:
print(X_train)

[[6.4 3.1 5.5 1.8]
 [5.4 3.0 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.0 4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.0 2.7 5.1 1.6]
 [5.9 3.0 4.2 1.5]
 [5.8 2.6 4.0 1.2]
 [6.8 3.0 5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.0 3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.0 2.0 3.5 1.0]
 [6.5 3.0 5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.0 2.2 5.0 1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.0 6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.0 1.9]
 [7.0 3.2 4.7 1.4]
 [6.5 3.0 5.2 2.0]
 [6.0 3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.0 1.3]
 [6.1 3.0 4.6 1.4]
 [7.2 3.2 6.0 1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.0 1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.0 4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.0 5.1 1.8]
 [5.1 2.5 3.0 1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.0 1.

In [206]:
print(y_train)

[2 1 0 2 2 1 0 1 1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1
 2 0 0 2 1 0 0 1 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2
 2 0 0 0 1 1 0 0 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1 1
 1 1 0 0 0 2 1 2 0]


In [207]:
from sklearn.neighbors import KNeighborsClassifier
lr = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
lr.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [208]:
knn_pred = lr.predict(X_test)

In [209]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(knn_pred, y_test))
accuracy_score(knn_pred, y_test)

[[11  0  0]
 [ 0 12  0]
 [ 0  1  6]]


0.9666666666666667

In [210]:
print(y_test)
print(knn_pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 2 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [211]:
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf')
svc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [212]:
svc_pred = svc.predict(X_test)
print(confusion_matrix(svc_pred, y_test))
accuracy_score(svc_pred, y_test)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


1.0

In [213]:
print(y_test)
print(svc_pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [214]:
from sklearn.naive_bayes import GaussianNB
nbc = GaussianNB()
nbc.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [215]:
nbc_pred = nbc.predict(X_test)
print(confusion_matrix(nbc_pred, y_test))
accuracy_score(nbc_pred, y_test)

[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]


0.9666666666666667

In [216]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy')
dtc.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [217]:
dtc_pred = dtc.predict(X_test)
print(confusion_matrix(dtc_pred, y_test))
accuracy_score(dtc_pred, y_test)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


1.0

In [218]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [219]:
rfc_pred = rfc.predict(X_test)
print(confusion_matrix(rfc_pred, y_test))
accuracy_score(rfc_pred, y_test)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


1.0

###Conclusion 
######Both models, support vector classifier and decision tree classifier have perfect prediction accuracy score of 1.0